//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pubsEntities : DbContext
    {
        public pubsEntities()
            : base("name=pubsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<jobs> jobs { get; set; }
        public virtual DbSet<pub_info> pub_info { get; set; }
        public virtual DbSet<publishers> publishers { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<stores> stores { get; set; }
        public virtual DbSet<titleauthor> titleauthor { get; set; }
        public virtual DbSet<titles> titles { get; set; }
        public virtual DbSet<discounts> discounts { get; set; }
        public virtual DbSet<roysched> roysched { get; set; }
    }
}
